# Generated by Django 4.1.5 on 2023-03-29 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='نام')),
                ('Family', models.CharField(max_length=100, null=True, verbose_name='نام خانوادگی')),
                ('Email', models.EmailField(max_length=100, verbose_name='ایمیل')),
                ('Phone', models.CharField(max_length=11, verbose_name='شماره همراه')),
                ('ProfileImage', models.ImageField(null=True, upload_to='ProfileImage/', verbose_name='عکس پروفایل')),
                ('Gender', models.IntegerField(choices=[(1, 'مرد'), (2, 'زن'), (3, 'نظری ندارم')], null=True, verbose_name='جنسیت')),
                ('BornDate', models.DateField(null=True, verbose_name='تاریخ تولد')),
                ('Credit', models.IntegerField(default=0, verbose_name='اعتبار')),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربری')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
        ),
    ]
