# Generated by Django 4.1.5 on 2023-04-01 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ACOUNT', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='قم', max_length=200, verbose_name='آدرس')),
                ('phone', models.CharField(max_length=12, verbose_name='تلفن')),
                ('email', models.EmailField(max_length=50, verbose_name='ایمبل')),
            ],
            options={
                'verbose_name': 'درباره ما',
                'verbose_name_plural': 'درباره ما',
            },
        ),
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='موضوع')),
                ('email', models.EmailField(max_length=50, verbose_name='ایمبل')),
                ('context', models.TextField(verbose_name='پیام')),
                ('created_at', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'ارتباط با ما',
                'verbose_name_plural': 'ارتباط با ما',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Mainimages/', verbose_name='عکس')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='توضیحات')),
                ('position', models.IntegerField(blank=True, choices=[(1, 'بالا راست'), (2, 'بالا وسط'), (3, 'بالا چپ'), (4, 'وسط راست'), (5, 'وسط وسط'), (6, 'وسط چپ'), (7, 'پایین راست'), (8, 'پایین وسط'), (9, 'پایین چپ')], null=True, verbose_name='موقعیت')),
                ('title', models.IntegerField(blank=True, choices=[(1, 'لوگو'), (2, 'اسلایدر')], null=True, verbose_name='کاربرد')),
                ('pub_date', models.DateTimeField(blank=True, null=True, verbose_name='زمان انتشار')),
            ],
            options={
                'verbose_name': 'تصاویر',
                'verbose_name_plural': 'تصاویر',
            },
        ),
        migrations.CreateModel(
            name='Socialmedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='نام')),
                ('link', models.URLField(unique=True, verbose_name='لینک')),
            ],
            options={
                'verbose_name': 'رسانه',
                'verbose_name_plural': 'رسانه',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='موضوع')),
                ('message', models.TextField(verbose_name='پیام')),
                ('created_at', models.DateField(blank=True, null=True)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ACOUNT.profile', verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تیکت',
                'verbose_name_plural': 'تیکت',
            },
        ),
        migrations.CreateModel(
            name='HomeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slogen', models.CharField(max_length=300, verbose_name='شعار')),
                ('superiority', models.TextField(blank=True, null=True, verbose_name='برتری')),
                ('Logo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logo', to='BASE.images', verbose_name='عکس لوگو')),
                ('aboutus', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='BASE.aboutus', verbose_name='درباره ما')),
                ('image', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='photos', to='BASE.images', verbose_name='تصاویر')),
                ('sllider', models.ManyToManyField(to='BASE.images', verbose_name='اسلایدر')),
                ('socialmedia', models.ManyToManyField(to='BASE.socialmedia', verbose_name='شبکه های اجتماعی')),
            ],
            options={
                'verbose_name': 'صفحه اصلی',
                'verbose_name_plural': 'صفحه اصلی',
            },
        ),
    ]
